services:
  - type: web
    name: ai-skill-backend
    runtime: node
    plan: free
    buildCommand: bun install && bun run build
    startCommand: bun run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://kamal_jit97:icDRy58aAWt2SXfO@backand.bsgr9fs.mongodb.net/test?appName=backand
      - key: GEMINI_API_KEY
        value: AIzaSyAOPo3v8zmko2ZtDREHOQWUJXVLzqRq0Zw
      - key: JWT_SECRET
        value: fallback-secret-hash-here-for-dev
